[project]
name = "suffragists"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-generativeai>=0.8.3",
    "grpcio==1.67.1",
    "joblib>=1.4.2",
    "pandas>=2.2.3",
    "tqdm>=4.67.1",
]
